name       : haskell-easy-file
version    : 0.2.1
release    : 1
source     :
    - http://hackage.haskell.org/package/easy-file-0.2.1/easy-file-0.2.1.tar.gz : ff86e1b29284499bea5f1d0ff539b3ed64fa6d1a06c2243ca61f93be0202e56c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Cross-platform File handling for Unix/Mac/Windows
description: |
    Cross-platform File handling for Unix/Mac/Windows
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
